using Microsoft.EntityFrameworkCore;
using CVerify.API.Core.Entities;
using CVerify.API.Application.Exceptions;
using Npgsql;

namespace CVerify.API.Infrastructure.Persistence;

public class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        EnforceImmutableAuditLogs();
        try
        {
            return await base.SaveChangesAsync(cancellationToken);
        }
        catch (DbUpdateException ex) when (ex.InnerException is PostgresException pgEx && pgEx.SqlState == "23505")
        {
            if (pgEx.ConstraintName?.Contains("users_email") == true || pgEx.Message.Contains("users") || pgEx.Detail?.Contains("email") == true)
            {
                throw new DuplicateEmailException("A user with this email address already exists.", ex);
            }
            throw;
        }
    }

    public override async Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default)
    {
        EnforceImmutableAuditLogs();
        try
        {
            return await base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
        }
        catch (DbUpdateException ex) when (ex.InnerException is PostgresException pgEx && pgEx.SqlState == "23505")
        {
            if (pgEx.ConstraintName?.Contains("users_email") == true || pgEx.Message.Contains("users") || pgEx.Detail?.Contains("email") == true)
            {
                throw new DuplicateEmailException("A user with this email address already exists.", ex);
            }
            throw;
        }
    }

    private void EnforceImmutableAuditLogs()
    {
        var auditLogEntries = ChangeTracker.Entries<AuditLog>()
            .Where(e => e.State == EntityState.Modified || e.State == EntityState.Deleted);
        
        if (auditLogEntries.Any())
        {
            throw new InvalidOperationException("Audit logs are strictly immutable and cannot be updated or deleted.");
        }
    }

    public DbSet<User> Users => Set<User>();
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<Permission> Permissions => Set<Permission>();
    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();
    public DbSet<VerificationToken> VerificationTokens => Set<VerificationToken>();
    public DbSet<ResetPasswordToken> ResetPasswordTokens => Set<ResetPasswordToken>();
    public DbSet<OutboxMessage> OutboxMessages => Set<OutboxMessage>();
    public DbSet<AuditLog> AuditLogs => Set<AuditLog>();
    public DbSet<Conversation> Conversations => Set<Conversation>();
    public DbSet<Message> Messages => Set<Message>();
    public DbSet<AuthProvider> AuthProviders => Set<AuthProvider>();
    public DbSet<PasswordCredential> PasswordCredentials => Set<PasswordCredential>();
    public DbSet<Organization> Organizations => Set<Organization>();
    public DbSet<OrganizationMember> OrganizationMembers => Set<OrganizationMember>();
    public DbSet<OtpVerification> OtpVerifications => Set<OtpVerification>();
    public DbSet<VerificationLink> VerificationLinks => Set<VerificationLink>();


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Explicitly declare that primary keys are client-generated UUID v7s and not auto-generated by the database
        modelBuilder.Entity<User>().Property(u => u.Id).ValueGeneratedNever();
        modelBuilder.Entity<Role>().Property(r => r.Id).ValueGeneratedNever();
        modelBuilder.Entity<Permission>().Property(p => p.Id).ValueGeneratedNever();
        modelBuilder.Entity<RefreshToken>().Property(rt => rt.Id).ValueGeneratedNever();
        modelBuilder.Entity<VerificationToken>().Property(vt => vt.Id).ValueGeneratedNever();
        modelBuilder.Entity<ResetPasswordToken>().Property(rt => rt.Id).ValueGeneratedNever();
        modelBuilder.Entity<OutboxMessage>().Property(om => om.Id).ValueGeneratedNever();
        modelBuilder.Entity<AuditLog>().Property(al => al.Id).ValueGeneratedNever();
        modelBuilder.Entity<Conversation>().Property(c => c.Id).ValueGeneratedNever();
        modelBuilder.Entity<Message>().Property(m => m.Id).ValueGeneratedNever();
        modelBuilder.Entity<AuthProvider>().Property(ap => ap.Id).ValueGeneratedNever();
        modelBuilder.Entity<PasswordCredential>().Property(pc => pc.Id).ValueGeneratedNever();
        modelBuilder.Entity<Organization>().Property(o => o.Id).ValueGeneratedNever();
        modelBuilder.Entity<OrganizationMember>().Property(om => om.Id).ValueGeneratedNever();
        modelBuilder.Entity<OtpVerification>().Property(ov => ov.Id).ValueGeneratedNever();
        modelBuilder.Entity<VerificationLink>().Property(vl => vl.Id).ValueGeneratedNever();

        // Enable PostgreSQL Extensions
        modelBuilder.HasPostgresExtension("citext");
        modelBuilder.HasPostgresExtension("pgcrypto");

        // Map Enum
        modelBuilder.HasPostgresEnum<UserStatus>();

        // Configure User <-> Role (Many-to-Many via user_roles junction table)
        modelBuilder.Entity<User>()
            .HasMany(u => u.Roles)
            .WithMany(r => r.Users)
            .UsingEntity<Dictionary<string, object>>(
                "user_roles",
                j => j.HasOne<Role>().WithMany().HasForeignKey("role_id"),
                j => j.HasOne<User>().WithMany().HasForeignKey("user_id"),
                j =>
                {
                    j.Property<DateTimeOffset>("assigned_at").HasDefaultValueSql("NOW()");
                });

        // Configure Role <-> Permission (Many-to-Many)
        modelBuilder.Entity<Role>()
            .HasMany(r => r.Permissions)
            .WithMany(p => p.Roles)
            .UsingEntity<Dictionary<string, object>>(
                "role_permissions",
                j => j.HasOne<Permission>().WithMany().HasForeignKey("permission_id"),
                j => j.HasOne<Role>().WithMany().HasForeignKey("role_id"),
                j =>
                {
                    j.Property<DateTimeOffset>("assigned_at").HasDefaultValueSql("NOW()");
                });

        // Configure VerificationToken -> User (Many-to-One Cascade)
        modelBuilder.Entity<VerificationToken>()
            .HasOne(vt => vt.User)
            .WithMany()
            .HasForeignKey(vt => vt.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        // Configure ResetPasswordToken -> User (Many-to-One Cascade)
        modelBuilder.Entity<ResetPasswordToken>()
            .HasOne(rt => rt.User)
            .WithMany()
            .HasForeignKey(rt => rt.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        // Configure AuditLog -> User (Many-to-One SetNull)
        modelBuilder.Entity<AuditLog>()
            .HasOne(al => al.User)
            .WithMany()
            .HasForeignKey(al => al.UserId)
            .OnDelete(DeleteBehavior.SetNull);


        // Optimistic Concurrency Control mapping utilizing PostgreSQL xmin system column
        modelBuilder.Entity<User>()
            .Property(u => u.Version)
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .ValueGeneratedOnAddOrUpdate()
            .IsConcurrencyToken();

        modelBuilder.Entity<User>()
            .Property(u => u.SessionVersion)
            .HasColumnName("session_version")
            .HasDefaultValue(1)
            .IsRequired();

        modelBuilder.Entity<Role>()
            .Property(r => r.Version)
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .ValueGeneratedOnAddOrUpdate()
            .IsConcurrencyToken();

        modelBuilder.Entity<VerificationToken>()
            .Property(vt => vt.Version)
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .ValueGeneratedOnAddOrUpdate()
            .IsConcurrencyToken();

        modelBuilder.Entity<ResetPasswordToken>()
            .Property(rt => rt.Version)
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .ValueGeneratedOnAddOrUpdate()
            .IsConcurrencyToken();

        // Indexes
        modelBuilder.Entity<User>().HasIndex(u => u.Email).IsUnique().HasFilter("deleted_at IS NULL");
        modelBuilder.Entity<Role>().HasIndex(r => r.Name).IsUnique();
        modelBuilder.Entity<Permission>().HasIndex(p => p.Name).IsUnique();

        // Optimized Hierarchy Index
        modelBuilder.Entity<Permission>()
            .HasIndex(p => p.Name)
            .HasMethod("btree") // default, but for hierarchy we might use varchar_pattern_ops in SQL
            .HasOperators("varchar_pattern_ops");
            
        // Status filter index
        modelBuilder.Entity<User>()
            .HasIndex(u => u.Status)
            .HasFilter("deleted_at IS NULL")
            .HasDatabaseName("idx_users_active");

        // Optimized partial indexes for active tokens only (keeping indexes compact)
        modelBuilder.Entity<VerificationToken>()
            .HasIndex(vt => vt.TokenHash)
            .HasFilter("consumed_at IS NULL")
            .HasDatabaseName("idx_verification_tokens_active");

        modelBuilder.Entity<ResetPasswordToken>()
            .HasIndex(rt => rt.TokenHash)
            .HasFilter("consumed_at IS NULL")
            .HasDatabaseName("idx_reset_password_tokens_active");

        modelBuilder.Entity<OutboxMessage>()
            .HasIndex(om => om.CreatedAt)
            .HasFilter("processed_at IS NULL")
            .HasDatabaseName("idx_outbox_messages_pending");

        // Explicit Foreign Key indexes for optimized join queries and delete cascades
        modelBuilder.Entity<VerificationToken>()
            .HasIndex(vt => vt.UserId)
            .HasDatabaseName("idx_verification_tokens_user_id");

        modelBuilder.Entity<ResetPasswordToken>()
            .HasIndex(rt => rt.UserId)
            .HasDatabaseName("idx_reset_password_tokens_user_id");

        modelBuilder.Entity<AuditLog>()
            .HasIndex(al => al.UserId)
            .HasDatabaseName("idx_audit_logs_user_id");

        // Configure RefreshToken mapping and indexes explicitly
        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.ToTable("refresh_tokens");
            entity.Property(t => t.SessionId)
                .HasColumnName("session_id")
                .IsRequired();
            entity.Property(t => t.RememberMe)
                .HasColumnName("remember_me")
                .HasDefaultValue(false)
                .IsRequired();
            entity.Property(t => t.ReplacedByTokenId)
                .HasColumnName("replaced_by_token_id");

            entity.HasIndex(t => t.UserId).HasDatabaseName("idx_refresh_tokens_user_id");
            entity.HasIndex(t => t.SessionId).HasDatabaseName("idx_refresh_tokens_session_id");
            entity.HasIndex(t => t.ExpiresAt).HasDatabaseName("idx_refresh_tokens_expires_at");
        });

        // Configure Conversations
        modelBuilder.Entity<Conversation>(entity =>
        {
            entity.ToTable("conversations");
            entity.HasIndex(c => c.UserId).HasDatabaseName("idx_conversations_user_id");
            
            entity.HasOne(c => c.User)
                .WithMany()
                .HasForeignKey(c => c.UserId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Configure Messages
        modelBuilder.Entity<Message>(entity =>
        {
            entity.ToTable("messages");
            entity.Property(m => m.Role).HasConversion<string>();
            entity.Property(m => m.StreamingState).HasConversion<string>();
            
            entity.HasIndex(m => new { m.ConversationId, m.CreatedAt }).HasDatabaseName("idx_messages_conversation_id_created_at");
            
            entity.HasOne(m => m.Conversation)
                .WithMany(c => c.Messages)
                .HasForeignKey(m => m.ConversationId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // AuthProvider configurations
        modelBuilder.Entity<AuthProvider>(entity =>
        {
            entity.ToTable("auth_providers");
            entity.HasQueryFilter(ap => ap.DeletedAt == null);
            entity.HasIndex(ap => new { ap.ProviderName, ap.ProviderKey })
                  .IsUnique()
                  .HasFilter("deleted_at IS NULL")
                  .HasDatabaseName("idx_auth_providers_key_active");
            entity.HasIndex(ap => new { ap.UserId, ap.ProviderName })
                  .IsUnique()
                  .HasFilter("deleted_at IS NULL")
                  .HasDatabaseName("idx_auth_providers_user_type_active");
        });

        // PasswordCredential configurations
        modelBuilder.Entity<PasswordCredential>(entity =>
        {
            entity.ToTable("password_credentials");
            entity.HasQueryFilter(pc => pc.DeletedAt == null);
            entity.HasOne(pc => pc.User)
                  .WithMany(u => u.PasswordCredentials)
                  .HasForeignKey(pc => pc.UserId)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        // Organization configurations
        modelBuilder.Entity<Organization>(entity =>
        {
            entity.ToTable("organizations");
            entity.HasQueryFilter(o => o.DeletedAt == null);
            entity.HasIndex(o => o.Username)
                  .IsUnique()
                  .HasFilter("deleted_at IS NULL")
                  .HasDatabaseName("idx_organizations_username_active");
            entity.HasIndex(o => o.TaxCode)
                  .IsUnique()
                  .HasFilter("deleted_at IS NULL")
                  .HasDatabaseName("idx_organizations_tax_code_active");
        });

        // OrganizationMember configurations
        modelBuilder.Entity<OrganizationMember>(entity =>
        {
            entity.ToTable("organization_members");
            entity.HasQueryFilter(om => om.Organization.DeletedAt == null);
            entity.HasOne(om => om.Organization)
                  .WithMany(o => o.Members)
                  .HasForeignKey(om => om.OrganizationId)
                  .OnDelete(DeleteBehavior.Cascade);
            entity.HasOne(om => om.User)
                  .WithMany()
                  .HasForeignKey(om => om.UserId)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        // OtpVerification configurations
        modelBuilder.Entity<OtpVerification>(entity =>
        {
            entity.ToTable("otp_verifications");
            entity.HasIndex(ov => ov.ChallengeId)
                  .HasDatabaseName("idx_otp_verifications_challenge_id");
            entity.HasIndex(ov => ov.Email)
                  .HasDatabaseName("idx_otp_verifications_email");
        });

        // VerificationLink configurations
        modelBuilder.Entity<VerificationLink>(entity =>
        {
            entity.ToTable("verification_links");
            entity.HasQueryFilter(vl => vl.DeletedAt == null);
            entity.HasIndex(vl => vl.TokenHash)
                  .HasFilter("deleted_at IS NULL AND consumed_at IS NULL")
                  .HasDatabaseName("idx_verification_links_active");
        });
    }
}
