import { 
  LayoutDashboard,
  Building2, 
  ShieldAlert, 
  Users, 
  Shield, 
  FileText,
  Briefcase,
  MessageSquare,
  UserCircle,
  Orbit,
  ShieldCheck,
  Sparkles,
  GitFork,
  Folder,
  Compass,
  Target,
  Bookmark,
  Inbox,
  User,
  GraduationCap,
  Award,
  Trophy
} from 'lucide-react';
import { type NavigationNode } from '../types/navigation.types';

export const navigationConfig: NavigationNode[] = [
  {
    id: 'general-section',
    type: 'section',
    label: 'General',
    translationKey: 'common:dashboard.sections.general',
    children: [
      {
        id: 'job-board-group',
        type: 'group',
        label: 'Job Board',
        translationKey: 'common:dashboard.jobBoard',
        href: '/jobs',
        icon: Briefcase,
        children: [
          {
            id: 'jobs-explore',
            type: 'item',
            label: 'Explore',
            translationKey: 'common:dashboard.exploreJobs',
            href: '/jobs',
            icon: Compass,
            exactMatch: true,
          },
          {
            id: 'jobs-recommended',
            type: 'item',
            label: 'Recommended',
            translationKey: 'common:dashboard.recommendedJobs',
            href: '/jobs?tab=recommended',
            icon: Target,
          },
          {
            id: 'jobs-saved',
            type: 'item',
            label: 'Saved',
            translationKey: 'common:dashboard.savedJobs',
            href: '/jobs?tab=saved',
            icon: Bookmark,
          },
          {
            id: 'jobs-applied',
            type: 'item',
            label: 'Applied',
            translationKey: 'common:dashboard.appliedJobs',
            href: '/jobs?tab=applied',
            icon: Inbox,
          },
        ],
      },
      {
        id: 'forum',
        type: 'item',
        label: 'Forum',
        translationKey: 'common:dashboard.forum',
        href: '/forum',
        icon: MessageSquare,
      },
      {
        id: 'organizations',
        type: 'item',
        label: 'Organizations',
        translationKey: 'common:dashboard.organizations',
        href: '/workspace/organizations',
        icon: Building2,
      },
      {
        id: 'ranking-group',
        type: 'group',
        label: 'Leaderboard',
        translationKey: 'common:dashboard.rankingGroup',
        href: '/ranking/insights',
        icon: Trophy,
        children: [
          {
            id: 'ranking-insights',
            type: 'item',
            label: 'Insights',
            translationKey: 'common:dashboard.rankingInsights',
            href: '/ranking/insights',
            icon: Sparkles,
          },
          {
            id: 'ranking-candidates',
            type: 'item',
            label: 'Rankings',
            translationKey: 'common:dashboard.ranking',
            href: '/ranking',
            icon: Trophy,
            exactMatch: true,
          },
        ],
      },
    ],
  },
  {
    id: 'candidate-section',
    type: 'section',
    label: 'Candidate',
    translationKey: 'common:dashboard.sections.candidate',
    requiredRoles: ['USER', 'ADMIN'],
    children: [
      {
        id: 'candidate-dashboard',
        type: 'item',
        label: 'Dashboard',
        translationKey: 'common:dashboard.candidateDashboard',
        href: '/user',
        icon: LayoutDashboard,
      },
      {
        id: 'candidate-profile',
        type: 'item',
        label: 'Professional Profile',
        translationKey: 'common:dashboard.profile',
        href: '/user/profile',
        icon: UserCircle,
      },
      {
        id: 'candidate-cv-group',
        type: 'group',
        label: 'My CV',
        translationKey: 'common:dashboard.cv',
        href: '/cv',
        icon: FileText,
        children: [
          {
            id: 'cv-overview',
            type: 'item',
            label: 'Overview',
            translationKey: 'common:cvManagement.overview',
            href: '/cv',
            icon: FileText,
            exactMatch: true,
          },
          {
            id: 'cv-basic-info',
            type: 'item',
            label: 'Basic Information',
            translationKey: 'common:cvManagement.sectionBasicInfo',
            href: '/cv?tab=basic-info',
            icon: User,
          },
          {
            id: 'cv-skills',
            type: 'item',
            label: 'Target Skills',
            translationKey: 'common:cvManagement.sectionSkills',
            href: '/cv?tab=skills',
            icon: Sparkles,
          },
          {
            id: 'cv-projects',
            type: 'item',
            label: 'Linked Projects',
            translationKey: 'common:cvManagement.sectionProjects',
            href: '/cv?tab=projects',
            icon: Folder,
          },
          {
            id: 'cv-experience',
            type: 'item',
            label: 'Work Experience',
            translationKey: 'common:cvManagement.sectionExperience',
            href: '/cv?tab=experience',
            icon: Briefcase,
          },
          {
            id: 'cv-education',
            type: 'item',
            label: 'Education',
            translationKey: 'common:cvManagement.sectionEducation',
            href: '/cv?tab=education',
            icon: GraduationCap,
          },
          {
            id: 'cv-achievements',
            type: 'item',
            label: 'Achievements & Certificates',
            translationKey: 'common:cvManagement.sectionAchievements',
            href: '/cv?tab=achievements',
            icon: Award,
          },
          {
            id: 'cv-preferences',
            type: 'item',
            label: 'Career Preferences',
            translationKey: 'common:cvManagement.sectionPreferences',
            href: '/cv?tab=preferences',
            icon: Target,
          },
        ],
      },
    ],
  },
  {
    id: 'intelligence-section',
    type: 'section',
    label: 'Intelligence',
    translationKey: 'common:dashboard.sections.intelligence',
    requiredRoles: ['USER', 'ADMIN'],
    children: [
      {
        id: 'intelligence-capability-graph',
        type: 'item',
        label: 'Capability Graph',
        translationKey: 'common:dashboard.capabilityGraph',
        href: '/intelligence/capability-graph',
        icon: Orbit,
      },
      {
        id: 'intelligence-trust-score',
        type: 'item',
        label: 'Trust Score',
        translationKey: 'common:dashboard.trustScore',
        href: '/intelligence/trust-score',
        icon: ShieldCheck,
      },
      {
        id: 'intelligence-ai-analysis',
        type: 'item',
        label: 'AI Analysis',
        translationKey: 'common:dashboard.aiAnalysis',
        href: '/intelligence/ai-analysis',
        icon: Sparkles,
      },
      {
        id: 'intelligence-repositories',
        type: 'item',
        label: 'Repositories',
        translationKey: 'common:dashboard.repositories',
        href: '/settings/source-code-providers',
        icon: GitFork,
      },
    ],
  },
  {
    id: 'business-section',
    type: 'section',
    label: 'Business',
    translationKey: 'common:dashboard.sections.business',
    requiredRoles: ['BUSINESS', 'ADMIN'],
    children: [
      {
        id: 'business-dashboard',
        type: 'item',
        label: 'Dashboard',
        translationKey: 'common:dashboard.businessDashboard',
        href: '/business',
        icon: Building2,
      },
    ],
  },
  {
    id: 'admin-section',
    type: 'section',
    label: 'Administration',
    translationKey: 'common:dashboard.systemAdmin',
    requiredRoles: ['ADMIN'],
    children: [
      {
        id: 'admin-group',
        type: 'group',
        label: 'System Admin',
        translationKey: 'common:admin.systemAdmin',
        icon: ShieldAlert,
        children: [
          {
            id: 'admin-overview',
            type: 'item',
            label: 'Admin',
            translationKey: 'common:admin.dashboard',
            href: '/admin',
            exactMatch: true,
            icon: LayoutDashboard,
          },
          {
            id: 'admin-users',
            type: 'item',
            label: 'Users',
            translationKey: 'common:admin.users',
            href: '/admin/users',
            icon: Users,
            requiredPermissions: ['users:view:list'],
          },
          {
            id: 'admin-roles',
            type: 'item',
            label: 'Roles Matrix',
            translationKey: 'common:admin.rolesMatrix',
            href: '/admin/roles',
            icon: Shield,
            requiredPermissions: ['roles:view:list'],
          },
          {
            id: 'admin-audit-logs',
            type: 'item',
            label: 'Audit Trail',
            translationKey: 'common:admin.auditTrail',
            href: '/admin/audit-logs',
            icon: FileText,
            requiredPermissions: ['ai:audit:view'],
          },
        ],
      },
    ],
  },
];
