name: Deploy Frontend Design to GitHub Pages

on:
  push:
    branches:
      - CVerify-uat # Kích hoạt khi bạn push code lên đúng nhánh này của nhóm

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Deploy sang branch gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: CVerify/Frontend_design # Đường dẫn chuẩn: Đi vào thư mục CVerify rồi mới đến Frontend_design
          branch: gh-pages